# Generated by Django 6.0.5 on 2026-05-29 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoArtesanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('bijuteria', 'Bijuteria'), ('decoracao', 'Decoração'), ('moda', 'Moda'), ('ceramica', 'Cerâmica'), ('papelaria', 'Papelaria'), ('outros', 'Outros')], default='outros', max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('unitaria', 'Unitária'), ('encomenda', 'Encomenda'), ('pacote', 'Pacote')], max_length=30)),
                ('condicoes_pagamento', models.CharField(max_length=200)),
                ('prazo_producao_dias', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_venda', to='produtos.produtoartesanal')),
            ],
        ),
    ]
